### ISSUE TITLE
使用问题

### ISSUE THREAD

**Issue by Abs-11001** [dsppman/Taper#1]
大佬，您好，请问如何让它自动回复消息，我在日志里面看到了发送过来的信息，但是似乎无法自动回复

**Comment by dsppman** [comment]
编写插件调用发送文本消息函数即可

**Comment by Abs-11001** [comment]
谢谢您的回复。可以具体一点吗  ，有点找不到在哪

**Comment by dsppman** [comment]
这个是开源框架，主要是学习为目的，没有使用文档，你可以看看代码里面是如何调用的呢
